// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package inout

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson61e0ab13DecodeShortenerInternalAppHandlerInout(in *jlexer.Lexer, out *OutputURL) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "result":
			out.Result = string(in.String())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson61e0ab13EncodeShortenerInternalAppHandlerInout(out *jwriter.Writer, in OutputURL) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		out.String(string(in.Result))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OutputURL) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson61e0ab13EncodeShortenerInternalAppHandlerInout(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OutputURL) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson61e0ab13EncodeShortenerInternalAppHandlerInout(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OutputURL) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson61e0ab13DecodeShortenerInternalAppHandlerInout(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OutputURL) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson61e0ab13DecodeShortenerInternalAppHandlerInout(l, v)
}
func easyjson61e0ab13DecodeShortenerInternalAppHandlerInout1(in *jlexer.Lexer, out *ExternalOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "correlation_id":
			out.ExternalID = string(in.String())
		case "short_url":
			out.ShortURL = string(in.String())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson61e0ab13EncodeShortenerInternalAppHandlerInout1(out *jwriter.Writer, in ExternalOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"correlation_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ExternalID))
	}
	{
		const prefix string = ",\"short_url\":"
		out.RawString(prefix)
		out.String(string(in.ShortURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExternalOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson61e0ab13EncodeShortenerInternalAppHandlerInout1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExternalOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson61e0ab13EncodeShortenerInternalAppHandlerInout1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExternalOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson61e0ab13DecodeShortenerInternalAppHandlerInout1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExternalOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson61e0ab13DecodeShortenerInternalAppHandlerInout1(l, v)
}
func easyjson61e0ab13DecodeShortenerInternalAppHandlerInout2(in *jlexer.Lexer, out *ExternalBatchOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(ExternalBatchOutput, 0, 2)
			} else {
				*out = ExternalBatchOutput{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 ExternalOutput
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson61e0ab13EncodeShortenerInternalAppHandlerInout2(out *jwriter.Writer, in ExternalBatchOutput) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v ExternalBatchOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson61e0ab13EncodeShortenerInternalAppHandlerInout2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExternalBatchOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson61e0ab13EncodeShortenerInternalAppHandlerInout2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExternalBatchOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson61e0ab13DecodeShortenerInternalAppHandlerInout2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExternalBatchOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson61e0ab13DecodeShortenerInternalAppHandlerInout2(l, v)
}
